apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterCrawler
metadata:
  name: ecr
spec:
  container:
    image: crawlers
    name: ecr
    resources: {}
    volumeMounts:
    - mountPath: /ocular/aws/config
      name: ecr-file-secrets
      readOnly: true
      subPath: aws-config
  parameters:
  - default: ""
    description: AWS region of the ECR repository. Defaults to the region configured
      in the AWS SDK if empty.
    name: AWS_REGION
  - default: ""
    description: ARN of the role to assume for accessing the ECR repository. Optional.
    name: AWS_PROFILE
  - default: "1"
    description: Maximum number of tags (versions) to retrieve per image. Will retrieve
      the latest N tags for each ECR image and start a new pipeline for each. Set
      to 0 to retrieve all versions. Defaults to 1.
    name: RECENT_TAG_LIMIT
  volumes:
  - name: ecr-file-secrets
    secret:
      optional: true
      secretName: crawler-secrets
