apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterCrawler
metadata:
  name: ghcr
spec:
  container:
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          key: github-token
          name: crawler-secrets
          optional: true
    - name: GITHUB_APP_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          key: github-app-private-key
          name: crawler-secrets
          optional: true
    - name: GITHUB_APP_ID
      valueFrom:
        secretKeyRef:
          key: github-app-id
          name: crawler-secrets
          optional: true
    image: crawlers
    name: ghcr
    resources: {}
  parameters:
  - description: Comma-separated list of Docker Hub organizations to crawl.
    name: GITHUB_ORGS
  - default: "1"
    description: Maximum number of tags (versions) to retrieve per image. Will retrieve
      the latest N tags for each GHCR image and start a new pipeline for each. Set
      to 0 to retrieve all versions. Defaults to 1.
    name: RECENT_TAG_LIMIT
