apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterCrawler
metadata:
  name: github
spec:
  container:
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          key: github-token
          name: crawler-secrets
          optional: true
    - name: GITHUB_APP_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          key: github-app-private-key
          name: crawler-secrets
          optional: true
    - name: GITHUB_APP_ID
      valueFrom:
        secretKeyRef:
          key: github-app-id
          name: crawler-secrets
          optional: true
    image: crawlers
    name: github
    resources: {}
  parameters:
  - description: Comma-separated list of GitLab groups to crawl.
    name: GITHUB_ORGS
  - default: "false"
    description: If set to anything but '0' or 'false', forked repositories will be
      skipped.
    name: SKIP_FORKS
