apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterCrawler
metadata:
  name: static-list
spec:
  container:
    image: crawlers
    name: static-list
    resources: {}
  parameters:
  - description: New line separated list of target identifiers to crawl.
    name: TARGET_IDENTIFIERS
