version: "2"
linters:
  settings:
    gosec:
      excludes:
        - G107 # Url provided to HTTP request as taint input
        - G115 # Potential integer overflow when converting between integer types
  enable:
    - errname
    - exhaustive
    - goconst
    - gocritic
    - gosec
    - misspell
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines