repos:
  - repo: https://github.com/golangci/golangci-lint/
    rev: v2.1.6
    hooks:
      - id: golangci-lint-full
        name: golangci-lint
      - id: golangci-lint-fmt
        name: golangci-lint fmt