services:
  default-downloaders:
    image: "${OCULAR_IMAGE_REGISTRY:-ghcr.io}/${OCULAR_DEFAULT_DOWNLOADER_IMAGE_REPOSITORY:-crashappsec/ocular-default-downloaders}:${OCULAR_IMAGE_TAG:-local}"
    build:
      secrets:
        - netrc
      args:
        - "LDFLAGS=${LDFLAGS:-}"
        - "INTEGRATION=downloaders"
      platforms:
        - linux/amd64
        - linux/arm64
      context: .
      tags:
        - "${OCULAR_IMAGE_REGISTRY:-ghcr.io}/${OCULAR_DEFAULT_DOWNLOADER_IMAGE_REPOSITORY:-crashappsec/ocular-default-downloaders}:${OCULAR_IMAGE_TAG:-local}"
  default-crawlers:
    image: "${OCULAR_IMAGE_REGISTRY:-ghcr.io}/${OCULAR_DEFAULT_CRAWLER_IMAGE_REPOSITORY:-crashappsec/ocular-default-crawlers}:${OCULAR_IMAGE_TAG:-local}"
    build:
      secrets:
        - netrc
      args:
        - "LDFLAGS=${LDFLAGS:-}"
        - "INTEGRATION=crawlers"
      platforms:
        - linux/amd64
        - linux/arm64
      context: .
      tags:
        - "${OCULAR_IMAGE_REGISTRY:-ghcr.io}/${OCULAR_DEFAULT_CRAWLER_IMAGE_REPOSITORY:-crashappsec/ocular-default-crawlers}:${OCULAR_IMAGE_TAG:-local}"
  default-uploaders:
    image: "${OCULAR_IMAGE_REGISTRY:-ghcr.io}/${OCULAR_DEFAULT_UPLOADER_IMAGE_REPOSITORY:-crashappsec/ocular-default-uploaders}:${OCULAR_IMAGE_TAG:-local}"
    build:
      secrets:
        - netrc
      args:
        - "LDFLAGS=${LDFLAGS:-}"
        - "INTEGRATION=uploaders"
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
        - "${OCULAR_IMAGE_REGISTRY:-ghcr.io}/${OCULAR_DEFAULT_UPLOADER_IMAGE_REPOSITORY:-crashappsec/ocular-default-uploaders}:${OCULAR_IMAGE_TAG:-local}"
secrets:
  netrc:
    environment: NETRC