apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterDownloader
metadata:
  name: npm
spec:
  container:
    command:
    - /entrypoint
    image: downloaders
    imagePullPolicy: IfNotPresent
    name: npm
    resources: {}
